---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

## step 12. 1
- Abhinav's notes: made a folder called Lab 1.

## step 12.2
- Abhinav's notes: Made a repo on Github for Team 5. Then coppied the html link of the repo from Github

## step 12.3
- Abhinav's notes: I changed the directory to Lab 1 in the terminal. Then cloned the repo by typing git clone https://github.com/DS202-at-ISU/s2026-ds2020-lab1-team5lab1.git. After doing that I opened the project in RStudios. Then opened the README.Rmd to make changes to the readme. 

# step 12.4 
- Abhinav's notes: made local changes to the Readme. Added a line called "Abhinav's notes: This is a line from RStudio" and saved the file. After saving the file, I did get add . to add all the changes files. Then I typed git commit -m "Step 12.2 done by Abhinav" to commit all the changes. 

# step 12.5
- Abhinav's notes: After commiting all my changes, I pushed it to github by typing git push origin main. So this would push it straight to the main branch in the repo in github. 

#step 12.6
- Abhinav's notes: After pushing the changes, I chcked the repo to see if my changes got pushed and it did. There was a commit and the change was that I added "Abhinav's notes: this is a line from RStudio" in the README.Rmd.


# All Responses
- Abhinav's notes: This is a line from RStudio
- Trey's notes: This is a line from RStudio
- Kate's notes: This is a line from RStudio
- Keaton's notes: This is a line from RStudio
